### ISSUE TITLE
Bug in de-serialization of cv2 numpy image array

### ISSUE THREAD

**Issue by vishal-keshav** [kalaspuffar/tensorflow-data#1]
The commented code in train.py does not print the image as was before serialization!
Upon printing out the image through imshow, it just prints white washed image.

```
sess = tf.Session()
sess.run(tf.global_variables_initializer())
features, labels = train_input_fn()

img, label = sess.run([features['image'], labels])
print(img.shape, label.shape)

# Loop over each example in batch
for i in range(img.shape[0]):
    cv2.imshow('image', img[i])
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    print('Class label ' + str(np.argmax(label[i])))
```

**Comment by kalaspuffar** [comment]
Hi Vishal.

Sorry that my instructions in the comment might have been a bit vague. It actually works if you have the image data. But as I cast the image data to float in the parser it will not be the correct data to be printed in this commented code.

So to view the images you need to comment out this line in the parser
image = tf.cast(image, tf.float32)

Hope this helps.

Best regards
Daniel

**Comment by vishal-keshav** [comment]
Hi Daniel,

Thanks a lot! It does work. I somehow missed that original image was serialized from uint8 to string (or bytes) and reverse has to be done in de-serialization step.

Cheers,
Vishal
