### ISSUE TITLE
What is accuracy of your classifier?

### ISSUE THREAD

**Issue by thedanzjl** [kalaspuffar/tensorflow-data#2]
Hello. Firstly, thank you for your effort and your code. Could you share your result metrics like accuracy? The deal is that I copy-pasted your code and have a bug that the model classifies everything as a dog.

**Comment by kalaspuffar** [comment]
Hi Danil.

I think I said something like 76% or something in the video but I can be remembering the wrong value. Let me run it again.

Best regards
Daniel

**Comment by kalaspuffar** [comment]
Well ran it for a while more and seems like the model is perhaps not good for this or maybe I need to do more work on the images.

{'accuracy': 0.7143716, 'loss': 2.9237928, 'global_step': 81852}

**Comment by thedanzjl** [comment]
Thank you. Now I understand the bug is not related to your code.
