### ISSUE TITLE
Getting Error on building bazel from anaconda env

### ISSUE THREAD

**Issue by tahercoolguy** [kalaspuffar/tensorflow-data#6]
bazel build //tensorflow/contrib/lite/toco:toco
ERROR: The 'build' command is only supported from within a workspace.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".

can you please help . How to sort out this problem . Because i am new to bazel

**Comment by kalaspuffar** [comment]
First of do you run the command from your tensorflow directory?
Second if you run bazel on Windows you need to start the build directive with /// instead of //

Lastly, I'm not sure one could build toco in Windows and I never got anaconda working when I tried.
